```puml
@startuml
class Menu {
  - productService: ProductService
  - guidanceService: RecyclingGuidanceService
  + startLoop(): void
  # displayOptions(): void
  # handleUserInput(): void
}

class ProductService {
  + createProduct(String ... args): Product
  + fetchProduct(name: String): Product
  + listProducts(): List<Product>
  + recyclingGuidance(p: Product): List<Strings>
  + enviromentalImpact(p: Product): double
  + enviromentalImpact(p: Product, Weighted: bool): double
}

class MaterialService {
  + createMaterial(String ... args): void
  + fetchMaterial(name: String): material
}

interface EnvironmentalImpactCalculator {
  + calculate(p: Product): double
}

class WeightedByLifespanStrategy {
  + calculate(p: Product): double
}

class SimpleSumStrategy {
  + calculate(p: Product): double
}

class Product implements ProductRepository{
  - name: String
  - category: String
  - estimatedLifespan: Integer
  - materials: List<Material>
  + getMaterials(): List<Material>
}

class Material implements MaterialRepository{
  - name: String
  - impactValue: Integer
  - recyclingGuidance: List<String>
}

class RecyclingGuidanceService {
  + fetchGuidance(p: Product): List<String>
}

interface Repository {
  + create(): void
  + read(name: String): Object
  + update(attribute: String, value: String): void
  + delete():void
  + fetchAll(): List<Object>
}

abstract class ProductRepository {
  + create(): void
  + read(name: String): Product
  + update(attribute: String, value: String): void
  + delete(): void
  + fetchAll(): List<Product>
}

abstract class MaterialRepository {
  + create(): void
  + read(name: String): Material
  + update(attribute: String, value: String): void
  + delete(): void
  + fetchAll(): List<Material>
}

class DatabaseManager {
  
}


Menu --> ProductService : calls
Menu --> MaterialService : calls

ProductService --> Product : call
ProductService --> RecyclingGuidanceService : calls
ProductService --> EnvironmentalImpactCalculator : calls

MaterialService --> Material : fetches

RecyclingGuidanceService --> Product : fetches

EnvironmentalImpactCalculator <|.. SimpleSumStrategy : implements
EnvironmentalImpactCalculator <|.. WeightedByLifespanStrategy : implements

EnvironmentalImpactCalculator ..> Product : analyzes

Repository <|.. ProductRepository : implements
Repository <|.. MaterialRepository : implements

Product "*" o-- "*" Material : contains

MaterialRepository --> DatabaseManager : calls
ProductRepository --> DatabaseManager : calls
@enduml
```