/*
 * This source file was generated by the Gradle 'init' task
 */
package se.hkr.ood;

import se.hkr.ood.presentation.Menu;

public class App {
    public static void main(String[] args) {
        Menu.startLoop();
    }
}
