/*
 * This source file was generated by the Gradle 'init' task
 */
package se.hkr.ood;

import se.hkr.ood.infrastructure.DatabaseManager;
import se.hkr.ood.presentation.Menu;

public class App {
    public static void main(String[] args) throws Exception {
        try {
            DatabaseManager.init();
        } catch (Exception e) {
            System.err.println("Failed to initialize database: " + e.getMessage());
            return;
        }
        
        Menu.startLoop();
    }
}
