/*
 * This source file was generated by the Gradle 'init' task
 */
package se.hkr.ood;

import org.junit.jupiter.api.Test;

import se.hkr.ood.App;
import se.hkr.ood.domain.Material;
import se.hkr.ood.domain.Product;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

class AppTest {
    @Test
    void MaterialCanGetGuidance() {
        Material mat = new Material();
        String name = "Glass Bottle";
        int impact = 40;
        List<String> guidance = Arrays.asList("Rinse out residue", "Sort by color if required");

        mat.setName(name);
        mat.setImpactValue(impact);
        mat.setRecyclingGuidance(guidance);

        assertEquals(guidance, mat.getGuidance(), "Recycing guidance should be the same.");

    }

    @Test
    void MaterialCanHandleNullGuidance() {
        Material mat = new Material();
        
        mat.setRecyclingGuidance(null);
        
        assertNull(mat.getGuidance(), "Recycing guidance should be null.");
    }
}
